scan_interval: 3

triggers:
  WoWClassic.exe: game
  DuneSandbox.exe: game
  "SteamLaunch AppId=1203620": game # Enshrouded
  kcalc: ai

pills:
  default:
    scx: none
    tuned: desktop
  game:
    tuned: gaming
    scx: lavd 1
    nice: -10
  ai:
    tuned: accelerator-performance
    scx: bpfland
